blank_issues_enabled: false
contact_links:
  - name: 💬 Questions / Discussion
    url: https://github.com/siboMuc/kt-metadata-collection/discussions
    about: For general questions, use Discussions instead of an issue.
